version: '3.8'

services:
  api-gateway:
    build:
      context: .
      args:
        - JAR_FILE=/api-gateway/target/*.jar
    hostname: api-gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    depends_on:
      - discovery

  discovery:
    build:
      context: .
      args:
        - JAR_FILE=/discovery-service/target/*.jar
    hostname: discovery
    ports:
      - "8761:8761"

  review:
    build:
      context: .
      args:
        - JAR_FILE=/review-service/target/*.jar
    hostname: review-service
    ports:
      - "8083:8083"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    depends_on:
      - discovery

  movie:
    build:
      context: .
      args:
        - JAR_FILE=/movie-service/target/*.jar
    hostname: movie-service
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - review-service.baseUrl=http://api-gateway:8080/review-service
    depends_on:
      - discovery