version: '3.8'

services:
#  config:
#    build:
#      context: .
#      args:
#        - JAR_FILE=/discovery-service/target/*.jar
#    hostname: config
#    ports:
#      - "8888:8888"

  api-gateway:
    build:
      context: .
      args:
        - JAR_FILE=/api-gateway/target/*.jar
    hostname: api-gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.client.enabled=true

    depends_on:
      - discovery

  discovery:
    build:
      context: .
      args:
        - JAR_FILE=/discovery-service/target/*.jar
    hostname: discovery
    ports:
      - "8761:8761"
#    depends_on:
#      - config

  stock:
    build:
      context: .
      args:
        - JAR_FILE=/stock-quote/target/*.jar
    hostname: stock-quote
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.client.enabled=true
    depends_on:
      - discovery
