spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: stock-quote
          uri: lb://stock-quote
          predicates:
            - Path=/stock-quote/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    enabled: false

