version: '3.8'

services:
  config:
    build:
      context: ..
      args:
        - JAR_FILE=/discovery-service/target/*.jar
    hostname: config
    ports:
      - "8888:8888"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  api-gateway:
    build:
      context: ..
      args:
        - JAR_FILE=/api-gateway/target/*.jar
    hostname: api-gateway
    ports:
      - "8080:8080"
    environment:
      - spring.zipkin.baseUrl=http://zipkin:9411
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.client.enabled=true

    depends_on:
      - discovery
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  discovery:
    build:
      context: ..
      args:
        - JAR_FILE=/discovery-service/target/*.jar
    hostname: discovery
    ports:
      - "8761:8761"
    depends_on:
      - config


  stock:
    build:
      context: ..
      args:
        - JAR_FILE=/stock-quote/target/*.jar
    hostname: stock-quote
    ports:
      - "8082:8082"
    environment:
      - spring.zipkin.baseUrl=http://zipkin:9411
      - spring.kafka.producer.bootstrap-servers=broker:29092
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.client.enabled=true
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  processor:
    build:
      context: ..
      args:
        - JAR_FILE=/processor/target/*.jar
    hostname: processor
    ports:
      - "8085:8085"
    environment:
      - spring.zipkin.baseUrl=http://zipkin:9411
      - spring.kafka.consumer.bootstrap-servers=broker:29092
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"





networks:
  default:
      name: external-network

