version: '3.8'

services:
#  config:
#    build:
#      context: .
#      args:
#        - JAR_FILE=/discovery-service/target/*.jar
#    hostname: config
#    ports:
#      - "8888:8888"
  api-gateway:
    build:
      context: ..
      args:
        - JAR_FILE=/api-gateway/target/*.jar
    hostname: api-gateway
    ports:
      - "8080:8080"
    environment:
      - spring.zipkin.baseUrl=http://zipkin:9411
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.client.enabled=true

    depends_on:
      - discovery

  discovery:
    build:
      context: ..
      args:
        - JAR_FILE=/discovery-service/target/*.jar
    hostname: discovery
    ports:
      - "8761:8761"
##    depends_on:
##      - config


  stock:
    build:
      context: ..
      args:
        - JAR_FILE=/stock-quote/target/*.jar
    hostname: stock-quote
    ports:
      - "8082:8082"
    environment:
      - spring.zipkin.baseUrl=http://zipkin:9411
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - eureka.client.enabled=true

networks:
  default:
      name: external-network
#    depends_on:
#      - zipkin
#
#  zipkin:
#    image: openzipkin/zipkin
#    profiles:
#      - debug
#    container_name: zipkin
#    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
#    environment:
#      - STORAGE_TYPE=mem
#      # Uncomment to disable scribe
#      # - SCRIBE_ENABLED=false
#      # Uncomment to enable self-tracing
#      - SELF_TRACING_ENABLED=true
#      # Uncomment to enable debug logging
#      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
#    ports:
#      # Port used for the Zipkin UI and HTTP Api
#      - "9411:9411"
#    depends_on:
#      - discovery
