spring:
  application:
    name: discovery
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    web:
      exposure: health