server:
  port: 8085

spring:
  application:
    name: processor
  zipkin:
    enable: true
  sleuth:
    sampler:
      percentage: 1
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: dane-king
      bootstrap-servers: localhost:9092

eureka:
  client:
    enabled: false

management:
  endpoint:
    web:
      exposure: health