server:
  port: 8082

review-service:
  baseUrl: http://localhost:8083/

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:movies
    driver-class-name: org.h2.Driver
    username: penta
    password: bar
