spring:
  application:
    name: stock-quote
  config:
    import: api.yml
server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092

eureka:
  client:
    enabled: false


management:
  endpoint:
    web:
      exposure: health