spring:
  application:
    name: stock-quote
  config:
    import: api.yml
  zipkin:
    enable: true
  sleuth:
    sampler:
      percentage: 1

server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092

eureka:
  client:
    enabled: false

management:
  endpoint:
    web:
      exposure: health