server:
  port: 8082

spring:
  application:
    name: stock-quote
  config:
    import: api.yml
  zipkin:
    enabled: false
  sleuth:
    sampler:
      percentage: 1
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: stock_holdings
      port: '27017'

eureka:
  client:
    enabled: false

management:
  endpoint:
    web:
      exposure: health