spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/config-repo
server:
  port: 8888
management:
  endpoint:
    web:
      exposure: health